#!/bin/sh
if [ $# -eq 0 ]
then
    docker run -it --rm -v ${PWD}:/mnt/ -w /mnt/ --name gulp aganzha/node:fn /root/node_modules/gulp/bin/gulp.js
else
    docker run -it --rm -v ${PWD}:/mnt/ -w /mnt/ --name gulp aganzha/node:fn /root/node_modules/gulp/bin/gulp.js $1
fi
