#!/bin/sh
if [ $# -eq 0 ]
then
    docker run -it --rm python:2.7-slim
else
    echo 'has args'
    P=$1
    DIR=${P%/*}
    EXE=${P##*/}
    echo $DIR
    echo $EXE
    docker run -it --rm -v ~/:/home/aganzha -v $DIR:/user/src/ aganzha/python:latest python /user/src/$EXE
fi
